def etfs():
    return {
        "^GSPC": "S&P 500",
        "^NDX": "Nasdaq 100",
        "^DJI": "Dow Jones Industrial Average",
        "^RUT": "Russell 2000",
        "^GSPTSE": "S&P/TSX Composite",
        "^FTSE": "FTSE 100",
        "^STOXX50E": "Euro Stoxx 50",
        "^FCHI": "CAC 40 (France)",
        "^GDAXI": "DAX 40 (Allemagne)",
        "^IBEX": "IBEX 35 (Espagne)",
        "^AEX": "AEX 25 (Pays-Bas)",
        "^SSMI": "SMI (Suisse)",
        "^N225": "Nikkei 225 (Japon)",
        "^HSI": "Hang Seng Index (Hong Kong)",
        "000001.SS": "SSE Composite (Chine)",
        "^TWII": "TSEC Weighted Index (Taïwan)",
        "^BSESN": "BSE Sensex (Inde)",
        "^AXJO": "ASX 200 (Australie)",
        "^BVSP": "IBOVESPA (Brésil)",
        "^MXX": "IPC Mexico",
        "^KS11": "KOSPI (Corée du Sud)",
        "^JKSE": "IDX Composite (Indonésie)",
        "^TA125.TA": "TA-125 (Israël)",
        "CL=F": "Pétrole brut (WTI)",
        "GC=F": "Or (Gold)",
        "SI=F": "Argent (Silver)",
        "BTC-EUR": "(Bitcoin)"
    }
